const categoris = [
  'All',
  'Concerts',
  'Sports',
  'Arts & Theater',
  'Family',
  'Film',
  'Miscellaneous',
  'Alternative',
  'Ballads/Romantic',
  'Blues',
  'Chanson Francaise',
  "Children's Music",
  'Classical',
  'Country',
  'Dance/Electronic',
  'Folk',
  'Hip-Hop/Rap',
  'Holiday',
  'Jazz',
  'Latin',
  'Medieval/Renaissance',
  'Metal',
  'New Age',
  'Other',
  'Pop',
  'R&B',
  'Reggae',
  'Religious',
  'Rock',
  'World',
  'Aquatics',
  'Athletic Races',
  'Badminton',
  'Bandy',
  'Baseball',
  'Basketball',
  'Biathlon',
  'Body Building',
  'Boxing',
  'Cricket',
  'Curling',
  'Cycling',
  'Equestrian',
  'eSports',
  'Extreme Sports',
  'Field Hockey',
  'Fitness',
  'Floorball',
  'Football',
  'Golf',
  'Gymnastics',
  'Handball',
  'Hockey',
  'Ice Skating',
  'Indoor Soccer',
  'Lacrosse',
  'Martial Arts',
  'Motorsports/Racing',
  'Netball',
  'Rodeo',
  'Roller Derby',
  'Roller Hockey',
  'Rugby',
  'Ski Jumping',
  'Skiing',
  'Soccer',
  'Softball',
  'Squash',
  'Surfing',
  'Swimming',
  'Table Tennis',
  'Tennis',
  'Toros',
  'Track & Field',
  'Volleyball',
  'Waterpolo',
  'Wrestling',
  "Children's Theatre",
  'Circus & Specialty Acts',
  'Cultural',
  'Dance',
  'Fashion',
  'Fine Art',
  'Magic & Illusion',
  'Multimedia',
  'Opera',
  'Performance Art',
  'Puppetry',
  'Spectacular',
  'Variety',
  'Ice Shows',
  'Fairs/Festivals',
  "Latin Children's",
  'Miscellaneous/Family',
  'Film/Family',
];

export default categoris;
